#!/bin/bash

source /opt/ros/electric/setup.bash

export ROS_PACKAGE_PATH=/home/smp1/ros:/home/smp1/ros/sdsmt_bots:$ROS_PACKAGE_PATH
export ROS_IP=$(ifconfig wlan0 | grep 'inet addr' | awk '{print $2}' | awk -F: '{print $2}')
export ROS_MASTER_URI=http://172.16.1.10:11311
export ROBOT=smp1

rostopic list > /dev/null
while [ "$?" -eq "1" ]; do
	sleep 2
	export ROS_IP=$(ifconfig wlan0 | grep 'inet addr' | awk '{print $2}' | awk -F: '{print $2}')
	rostopic list > /dev/null
done

echo "Starting up..."
#/usr/bin/screen -dm -S smp1 roslaunch smp_mecanum_2dnav smp_mecanum_2dnav.launch
/usr/bin/screen -dm -S smp1 roslaunch smp_bringup smp_mecanum.launch

sleep 5
